logging:
  level:
    org.fpwei.line: debug
  file: all.log

org:
  fpwei:
    crawler:
      ptt:
        image:
          download:
            path: "/data/img/"
      task:
        beauty:
          cron: "0 */5 * * * *"

spring:
  datasource:
    url: "{spring.datasource.url}"
    username: "{spring.datasource.username}"
    password: "{spring.datasource.password}"


